# Generated by Django 5.1 on 2024-08-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_guest_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='date_time',
        ),
    ]
