# Generated by Django 5.1 on 2024-08-13 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter Your Name', max_length=30)),
                ('description', models.TextField(default='Desc', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('brand', models.CharField(default='Enter Your Brand', max_length=100)),
                ('category', models.CharField(choices=[('COMPUTER', 'Computer'), ('PHONE', 'Phone'), ('HOME', 'Home'), ('FOOD', 'Food'), ('KIDS', 'Kids')], default='', max_length=30)),
                ('ratings', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3)),
                ('stock', models.IntegerField(default=0)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
