# Generated by Django 5.0.6 on 2024-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_1',
            name='watch',
            field=models.ManyToManyField(to='pages.vedio'),
        ),
    ]
