# Generated by Django 5.0.6 on 2024-06-05 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_test_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 10, 56, 29, 816527)),
        ),
    ]
