# Generated by Django 5.0.6 on 2024-07-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='someone', max_length=50, null=True)),
                ('lname', models.CharField(default='someone', max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='o_s.track')),
            ],
        ),
    ]
